spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes:
                -   id: employeeModule
                    uri: lb://resource-service
                    predicates:
                        - Path=/resources/**
                -   id: songsModule
                    uri: lb://song-service
                    predicates:
                        - Path=/songs/**

server:
    port: 8080

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER_DEFAULT_ZONE:http://localhost:8761/eureka/}
