spring:
    application:
        name: song-service
    datasource:
        url: jdbc:postgresql://localhost:5432/songdb
        username: user
        password: secret
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8282
