spring:
    application:
        name: song-service
    datasource:
        url: ${SONG_DB_URL:jdbc:postgresql://localhost:5432/songdb}
        username: ${POSTGRES_USER:user}
        password: ${POSTGRES_PASSWORD:secret}
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8282
