spring:
    application:
        name: song-service
    datasource:
        url: ${SONG_DB_URL:jdbc:postgresql://localhost:5432/songdb}
        username: ${POSTGRES_USER:user}
        password: ${POSTGRES_PASSWORD:secret}
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8282

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER_DEFAULT_ZONE:http://localhost:8761/eureka/}
    instance:
        hostname: ${SONG_SERVICE_EUREKA_HOSTNAME:localhost}