spring:
    application:
        name: resource-service
    datasource:
        url: ${RESOURCE_DB_URL:jdbc:postgresql://localhost:5433/resourcedb}
        username: ${POSTGRES_USER:user}
        password: ${POSTGRES_PASSWORD:secret}
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8181

song-service:
    baseUrl: ${GATEWAY_SERVICE_URL:http://localhost:8080}/songs
    connectionTimeout: 1000
    readTimeout: 1000

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER_DEFAULT_ZONE:http://localhost:8761/eureka/}
    instance:
        hostname: ${RESOURCE_SERVICE_EUREKA_HOSTNAME:localhost}
