spring:
    application:
        name: resource-service
    datasource:
        url: jdbc:postgresql://localhost:5433/resourcedb
        username: user
        password: secret
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8181

song-service:
    baseUrl: http://localhost:8282/songs
    connectionTimeout: 1000
    readTimeout: 1000

logging:
    level:
        org:
            springframework:
                retry: debug