spring:
    application:
        name: resource-service
    datasource:
        url: ${RESOURCE_DB_URL:jdbc:postgresql://localhost:5433/resourcedb}
        username: ${POSTGRES_USER:user}
        password: ${POSTGRES_PASSWORD:secret}
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8181

song-service:
    baseUrl: ${SONG_SERVICE_BASE_URL:http://localhost:8282/songs}
    connectionTimeout: 1000
    readTimeout: 1000

logging:
    level:
        org:
            springframework:
                retry: debug